"""initial_schema

Revision ID: 1093b16c00af
Revises:
Create Date: 2026-07-02 18:46:35.268794
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = "1093b16c00af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtags",
        sa.Column("hashtag_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "fts_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', name)", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("hashtag_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=15), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=False),
        sa.Column("following_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followee_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["followee_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("follower_id", "followee_id"),
        sa.UniqueConstraint("follower_id", "followee_id", name="uq_follower_followee"),
    )
    op.create_table(
        "tweets",
        sa.Column("tweet_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=280), nullable=False),
        sa.Column(
            "fts_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tweet_id"),
    )
    op.create_index(op.f("ix_tweets_author_id"), "tweets", ["author_id"], unique=False)
    op.create_table(
        "tweet_hashtags",
        sa.Column("tweet_id", sa.UUID(), nullable=False),
        sa.Column("hashtag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["hashtag_id"], ["hashtags.hashtag_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tweet_id"], ["tweets.tweet_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tweet_id", "hashtag_id"),
        sa.UniqueConstraint("tweet_id", "hashtag_id", name="uq_tweet_hashtag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweet_hashtags")
    op.drop_index(op.f("ix_tweets_author_id"), table_name="tweets")
    op.drop_table("tweets")
    op.drop_table("follows")
    op.drop_table("users")
    op.drop_table("hashtags")
    # ### end Alembic commands ###
